/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/reference/countries': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ReferenceController_countries'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/reference/currencies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ReferenceController_currencies'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthController_liveness'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthController_readiness'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/sign-in': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_signIn'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/mfa/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_verifySecondFactor'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AuthController_me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/sign-out': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_signOut'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/mfa/enroll': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_enrollMfa'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/mfa/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_confirmMfa'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/password/forgot': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_forgotPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/password/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_resetPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/demo-accounts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AuthController_demoAccountsList'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/invitations/{token}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['InvitationAcceptanceController_preview'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/invitations/{token}/accept': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['InvitationAcceptanceController_accept'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tenants': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['TenantsController_list'];
    put?: never;
    post: operations['TenantsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tenants/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['TenantsController_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['TenantsController_update'];
    trace?: never;
  };
  '/api/v1/tenants/{id}/activate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['TenantsController_activate'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tenants/{id}/deactivate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['TenantsController_deactivate'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tenants/{id}/administrators': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['TenantsController_inviteAdministrator'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/invitations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['UsersController_invitations'];
    put?: never;
    post: operations['UsersController_invite'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['UsersController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['UsersController_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['UsersController_update'];
    trace?: never;
  };
  '/api/v1/users/{id}/deactivate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['UsersController_deactivate'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/{id}/reactivate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['UsersController_reactivate'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/{id}/roles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['UsersController_setRoles'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/roles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['RolesController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['SettingsController_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['SettingsController_update'];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  ReferenceController_countries: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code: string;
            nameEn: string;
            nameFr: string;
          }[];
        };
      };
    };
  };
  ReferenceController_currencies: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code: string;
            minorUnits: number;
          }[];
        };
      };
    };
  };
  HealthController_liveness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The API process is running. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'ok';
          };
        };
      };
    };
  };
  HealthController_readiness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description All dependencies answer. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'ok' | 'unavailable';
            checks: {
              [key: string]: 'up' | 'down';
            };
          };
        };
      };
      /** @description At least one dependency does not answer. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'ok' | 'unavailable';
            checks: {
              [key: string]: 'up' | 'down';
            };
          };
        };
      };
    };
  };
  AuthController_signIn: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** Format: email */
          email: string;
          password: string;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'SIGNED_IN' | 'MFA_REQUIRED';
          };
        };
      };
    };
  };
  AuthController_verifySecondFactor: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          code: string;
          /**
           * @default totp
           * @enum {string}
           */
          method: 'totp' | 'backup';
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'SIGNED_IN' | 'MFA_REQUIRED';
          };
        };
      };
    };
  };
  AuthController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            user: {
              /** Format: uuid */
              id: string;
              name: string;
              /** Format: email */
              email: string;
              /** @enum {string} */
              locale: 'en-GB' | 'fr-FR';
            };
            tenant: {
              /** Format: uuid */
              id: string;
              legalName: string;
            } | null;
            roles: (
              | 'PLATFORM_ADMIN'
              | 'ISSUER_ADMIN'
              | 'ISSUER_OPERATOR'
              | 'COMPLIANCE_OFFICER'
              | 'AUDITOR'
              | 'INVESTOR'
            )[];
            permissions: {
              [key: string]: 'all' | 'own';
            };
            portals: ('platform' | 'issuer' | 'investor')[];
            /** @enum {string} */
            homePortal: 'platform' | 'issuer' | 'investor';
            mfa: {
              enabled: boolean;
              required: boolean;
            };
            /** Format: date-time */
            sessionExpiresAt: string;
          };
        };
      };
    };
  };
  AuthController_signOut: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_enrollMfa: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          password: string;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            totpUri: string;
            secretKey: string;
            backupCodes: string[];
          };
        };
      };
    };
  };
  AuthController_confirmMfa: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          code: string;
        };
      };
    };
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_forgotPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** Format: email */
          email: string;
        };
      };
    };
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_resetPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          token: string;
          newPassword: string;
        };
      };
    };
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_demoAccountsList: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            password: string;
            totpValidForSeconds: number;
            accounts: {
              /** Format: email */
              email: string;
              name: string;
              /** @enum {string} */
              role:
                | 'PLATFORM_ADMIN'
                | 'ISSUER_ADMIN'
                | 'ISSUER_OPERATOR'
                | 'COMPLIANCE_OFFICER'
                | 'AUDITOR'
                | 'INVESTOR';
              /** @enum {string|null} */
              tenant: 'northwind' | 'contoso' | null;
              totpCode: string | null;
            }[];
          };
        };
      };
    };
  };
  InvitationAcceptanceController_preview: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: email */
            email: string;
            name: string;
            /** @enum {string} */
            roleCode:
              | 'PLATFORM_ADMIN'
              | 'ISSUER_ADMIN'
              | 'ISSUER_OPERATOR'
              | 'COMPLIANCE_OFFICER'
              | 'AUDITOR'
              | 'INVESTOR';
            tenantName: string | null;
            /** Format: date-time */
            expiresAt: string;
          };
        };
      };
    };
  };
  InvitationAcceptanceController_accept: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          password: string;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'SIGNED_IN' | 'MFA_REQUIRED';
          };
        };
      };
    };
  };
  TenantsController_list: {
    parameters: {
      query?: {
        q?: string;
        pageSize?: number;
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: {
              /** Format: uuid */
              id: string;
              legalName: string;
              tradeName: string | null;
              countryCode: string;
              baseCurrency: string;
              /** @enum {string} */
              defaultLocale: 'en-GB' | 'fr-FR';
              timezone: string;
              /** @enum {string} */
              organizationType: 'ISSUER' | 'ASSET_MANAGER' | 'FUND';
              /** @enum {string} */
              status: 'ACTIVE' | 'INACTIVE';
              version: number;
              /** Format: date-time */
              createdAt: string;
            }[];
            meta: {
              page: number;
              pageSize: number;
              total: number;
            };
          };
        };
      };
    };
  };
  TenantsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          legalName: string;
          tradeName?: string | null;
          countryCode: string;
          baseCurrency: string;
          /**
           * @default en-GB
           * @enum {string}
           */
          defaultLocale: 'en-GB' | 'fr-FR';
          /** @default Europe/Paris */
          timezone: string;
          /** @enum {string} */
          organizationType: 'ISSUER' | 'ASSET_MANAGER' | 'FUND';
          firstAdministrator: {
            /** Format: email */
            email: string;
            name: string;
            /**
             * @default en-GB
             * @enum {string}
             */
            locale: 'en-GB' | 'fr-FR';
          };
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            legalName: string;
            tradeName: string | null;
            countryCode: string;
            baseCurrency: string;
            /** @enum {string} */
            defaultLocale: 'en-GB' | 'fr-FR';
            timezone: string;
            /** @enum {string} */
            organizationType: 'ISSUER' | 'ASSET_MANAGER' | 'FUND';
            /** @enum {string} */
            status: 'ACTIVE' | 'INACTIVE';
            version: number;
            /** Format: date-time */
            createdAt: string;
          };
        };
      };
    };
  };
  TenantsController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            legalName: string;
            tradeName: string | null;
            countryCode: string;
            baseCurrency: string;
            /** @enum {string} */
            defaultLocale: 'en-GB' | 'fr-FR';
            timezone: string;
            /** @enum {string} */
            organizationType: 'ISSUER' | 'ASSET_MANAGER' | 'FUND';
            /** @enum {string} */
            status: 'ACTIVE' | 'INACTIVE';
            version: number;
            /** Format: date-time */
            createdAt: string;
          };
        };
      };
    };
  };
  TenantsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          legalName?: string;
          tradeName?: string | null;
          /** @enum {string} */
          defaultLocale?: 'en-GB' | 'fr-FR';
          timezone?: string;
          /** @enum {string} */
          organizationType?: 'ISSUER' | 'ASSET_MANAGER' | 'FUND';
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            legalName: string;
            tradeName: string | null;
            countryCode: string;
            baseCurrency: string;
            /** @enum {string} */
            defaultLocale: 'en-GB' | 'fr-FR';
            timezone: string;
            /** @enum {string} */
            organizationType: 'ISSUER' | 'ASSET_MANAGER' | 'FUND';
            /** @enum {string} */
            status: 'ACTIVE' | 'INACTIVE';
            version: number;
            /** Format: date-time */
            createdAt: string;
          };
        };
      };
    };
  };
  TenantsController_activate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            legalName: string;
            tradeName: string | null;
            countryCode: string;
            baseCurrency: string;
            /** @enum {string} */
            defaultLocale: 'en-GB' | 'fr-FR';
            timezone: string;
            /** @enum {string} */
            organizationType: 'ISSUER' | 'ASSET_MANAGER' | 'FUND';
            /** @enum {string} */
            status: 'ACTIVE' | 'INACTIVE';
            version: number;
            /** Format: date-time */
            createdAt: string;
          };
        };
      };
    };
  };
  TenantsController_deactivate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            legalName: string;
            tradeName: string | null;
            countryCode: string;
            baseCurrency: string;
            /** @enum {string} */
            defaultLocale: 'en-GB' | 'fr-FR';
            timezone: string;
            /** @enum {string} */
            organizationType: 'ISSUER' | 'ASSET_MANAGER' | 'FUND';
            /** @enum {string} */
            status: 'ACTIVE' | 'INACTIVE';
            version: number;
            /** Format: date-time */
            createdAt: string;
          };
        };
      };
    };
  };
  TenantsController_inviteAdministrator: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** Format: email */
          email: string;
          name: string;
          /**
           * @default en-GB
           * @enum {string}
           */
          locale: 'en-GB' | 'fr-FR';
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            expiresAt: string;
          };
        };
      };
    };
  };
  UsersController_invitations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string;
            /** @enum {string} */
            roleCode:
              | 'PLATFORM_ADMIN'
              | 'ISSUER_ADMIN'
              | 'ISSUER_OPERATOR'
              | 'COMPLIANCE_OFFICER'
              | 'AUDITOR'
              | 'INVESTOR';
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
          }[];
        };
      };
    };
  };
  UsersController_invite: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** Format: email */
          email: string;
          name: string;
          /**
           * @default en-GB
           * @enum {string}
           */
          locale: 'en-GB' | 'fr-FR';
          /** @enum {string} */
          roleCode:
            | 'PLATFORM_ADMIN'
            | 'ISSUER_ADMIN'
            | 'ISSUER_OPERATOR'
            | 'COMPLIANCE_OFFICER'
            | 'AUDITOR'
            | 'INVESTOR';
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            expiresAt: string;
          };
        };
      };
    };
  };
  UsersController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            locale: 'en-GB' | 'fr-FR';
            /** @enum {string} */
            status: 'ACTIVE' | 'INACTIVE';
            roles: (
              | 'PLATFORM_ADMIN'
              | 'ISSUER_ADMIN'
              | 'ISSUER_OPERATOR'
              | 'COMPLIANCE_OFFICER'
              | 'AUDITOR'
              | 'INVESTOR'
            )[];
            mfaEnabled: boolean;
            /** Format: date-time */
            lastLoginAt: string | null;
            /** Format: date-time */
            createdAt: string;
          }[];
        };
      };
    };
  };
  UsersController_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            locale: 'en-GB' | 'fr-FR';
            /** @enum {string} */
            status: 'ACTIVE' | 'INACTIVE';
            roles: (
              | 'PLATFORM_ADMIN'
              | 'ISSUER_ADMIN'
              | 'ISSUER_OPERATOR'
              | 'COMPLIANCE_OFFICER'
              | 'AUDITOR'
              | 'INVESTOR'
            )[];
            mfaEnabled: boolean;
            /** Format: date-time */
            lastLoginAt: string | null;
            /** Format: date-time */
            createdAt: string;
          };
        };
      };
    };
  };
  UsersController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name?: string;
          /** @enum {string} */
          locale?: 'en-GB' | 'fr-FR';
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            locale: 'en-GB' | 'fr-FR';
            /** @enum {string} */
            status: 'ACTIVE' | 'INACTIVE';
            roles: (
              | 'PLATFORM_ADMIN'
              | 'ISSUER_ADMIN'
              | 'ISSUER_OPERATOR'
              | 'COMPLIANCE_OFFICER'
              | 'AUDITOR'
              | 'INVESTOR'
            )[];
            mfaEnabled: boolean;
            /** Format: date-time */
            lastLoginAt: string | null;
            /** Format: date-time */
            createdAt: string;
          };
        };
      };
    };
  };
  UsersController_deactivate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            locale: 'en-GB' | 'fr-FR';
            /** @enum {string} */
            status: 'ACTIVE' | 'INACTIVE';
            roles: (
              | 'PLATFORM_ADMIN'
              | 'ISSUER_ADMIN'
              | 'ISSUER_OPERATOR'
              | 'COMPLIANCE_OFFICER'
              | 'AUDITOR'
              | 'INVESTOR'
            )[];
            mfaEnabled: boolean;
            /** Format: date-time */
            lastLoginAt: string | null;
            /** Format: date-time */
            createdAt: string;
          };
        };
      };
    };
  };
  UsersController_reactivate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            locale: 'en-GB' | 'fr-FR';
            /** @enum {string} */
            status: 'ACTIVE' | 'INACTIVE';
            roles: (
              | 'PLATFORM_ADMIN'
              | 'ISSUER_ADMIN'
              | 'ISSUER_OPERATOR'
              | 'COMPLIANCE_OFFICER'
              | 'AUDITOR'
              | 'INVESTOR'
            )[];
            mfaEnabled: boolean;
            /** Format: date-time */
            lastLoginAt: string | null;
            /** Format: date-time */
            createdAt: string;
          };
        };
      };
    };
  };
  UsersController_setRoles: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          roles: (
            | 'PLATFORM_ADMIN'
            | 'ISSUER_ADMIN'
            | 'ISSUER_OPERATOR'
            | 'COMPLIANCE_OFFICER'
            | 'AUDITOR'
            | 'INVESTOR'
          )[];
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            locale: 'en-GB' | 'fr-FR';
            /** @enum {string} */
            status: 'ACTIVE' | 'INACTIVE';
            roles: (
              | 'PLATFORM_ADMIN'
              | 'ISSUER_ADMIN'
              | 'ISSUER_OPERATOR'
              | 'COMPLIANCE_OFFICER'
              | 'AUDITOR'
              | 'INVESTOR'
            )[];
            mfaEnabled: boolean;
            /** Format: date-time */
            lastLoginAt: string | null;
            /** Format: date-time */
            createdAt: string;
          };
        };
      };
    };
  };
  RolesController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            code:
              | 'PLATFORM_ADMIN'
              | 'ISSUER_ADMIN'
              | 'ISSUER_OPERATOR'
              | 'COMPLIANCE_OFFICER'
              | 'AUDITOR'
              | 'INVESTOR';
            permissions: {
              code: string;
              /** @enum {string} */
              scope: 'all' | 'own';
            }[];
          }[];
        };
      };
    };
  };
  SettingsController_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            legalName: string;
            tradeName: string | null;
            countryCode: string;
            baseCurrency: string;
            /** @enum {string} */
            defaultLocale: 'en-GB' | 'fr-FR';
            timezone: string;
            /** @enum {string} */
            organizationType: 'ISSUER' | 'ASSET_MANAGER' | 'FUND';
            /** @enum {string} */
            status: 'ACTIVE' | 'INACTIVE';
            version: number;
            /** Format: date-time */
            createdAt: string;
          };
        };
      };
    };
  };
  SettingsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          tradeName?: string | null;
          /** @enum {string} */
          defaultLocale?: 'en-GB' | 'fr-FR';
          timezone?: string;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            id: string;
            legalName: string;
            tradeName: string | null;
            countryCode: string;
            baseCurrency: string;
            /** @enum {string} */
            defaultLocale: 'en-GB' | 'fr-FR';
            timezone: string;
            /** @enum {string} */
            organizationType: 'ISSUER' | 'ASSET_MANAGER' | 'FUND';
            /** @enum {string} */
            status: 'ACTIVE' | 'INACTIVE';
            version: number;
            /** Format: date-time */
            createdAt: string;
          };
        };
      };
    };
  };
}
