import { betterAuth } from 'better-auth';
import { drizzleAdapter } from 'better-auth/adapters/drizzle';
import { twoFactor } from 'better-auth/plugins/two-factor';
import { PASSWORD_MAX_LENGTH, PASSWORD_MIN_LENGTH } from '../domain/password-policy.js';
import { SESSION_IDLE_SECONDS, SESSION_REFRESH_SECONDS } from '../domain/session-policy.js';
import type { AuthDatabase } from './auth-database.js';
import { hashPassword, verifyPassword } from './password-hashing.js';
import { account, session, twoFactor as twoFactorTable, user, verification } from './schema.js';

export interface BetterAuthDependencies {
  /** BETTER_AUTH_SECRET: signs cookies and encrypts TOTP secrets. */
  secret: string;
  /** Address of the web app as seen by the browser (WEB_ORIGIN). */
  webOrigin: string;
  /** Other addresses of the same web app (WEB_ALTERNATE_ORIGINS). */
  alternateOrigins?: readonly string[];
  db: AuthDatabase;
  /** Sends the password reset email; Better Auth only provides the one-time token. */
  sendResetPassword: (data: { userId: string; email: string; token: string }) => Promise<void>;
}

/**
 * Better Auth (decision D-002) handles passwords, sessions and TOTP. It is never exposed directly:
 * the API's own routes call it (decision D-031), so that every answer follows SPEC §22.2 and the
 * API keeps control of lockout, rate limiting and audit.
 */
export function createBetterAuth({
  secret,
  webOrigin,
  alternateOrigins = [],
  db,
  sendResetPassword,
}: BetterAuthDependencies) {
  return betterAuth({
    appName: 'Veris Assets',
    secret,
    baseURL: webOrigin,
    trustedOrigins: [webOrigin, ...alternateOrigins],
    telemetry: { enabled: false },
    database: drizzleAdapter(db, {
      provider: 'pg',
      schema: { user, session, account, verification, twoFactor: twoFactorTable },
    }),
    emailAndPassword: {
      enabled: true,
      // B2B platform: accounts are only created through invitations.
      disableSignUp: true,
      minPasswordLength: PASSWORD_MIN_LENGTH,
      maxPasswordLength: PASSWORD_MAX_LENGTH,
      password: { hash: hashPassword, verify: verifyPassword },
      revokeSessionsOnPasswordReset: true,
      resetPasswordTokenExpiresIn: 60 * 60,
      sendResetPassword: ({ user: target, token }) =>
        sendResetPassword({ userId: target.id, email: target.email, token }),
    },
    session: {
      expiresIn: SESSION_IDLE_SECONDS,
      updateAge: SESSION_REFRESH_SECONDS,
      // Always read the session from the database, so that revocation is immediate.
      cookieCache: { enabled: false },
    },
    // Rate limiting is done by the API itself, with Redis (shared by every instance).
    rateLimit: { enabled: false },
    advanced: {
      cookiePrefix: 'va',
      useSecureCookies: webOrigin.startsWith('https://'),
      defaultCookieAttributes: { httpOnly: true, sameSite: 'lax', path: '/' },
      // Identifiers are UUID v7 generated by PostgreSQL (decision D-024).
      database: { generateId: 'uuid' },
      ipAddress: { ipAddressHeaders: ['x-forwarded-for'] },
    },
    plugins: [
      twoFactor({
        issuer: 'Veris Assets',
        totpOptions: { digits: 6, period: 30 },
        backupCodeOptions: { amount: 10 },
      }),
    ],
  });
}

export type BetterAuth = ReturnType<typeof createBetterAuth>;
export const BETTER_AUTH = Symbol('BETTER_AUTH');
