// Documents generated by the relay handlers (phase 15b), read directly in the test database.
import type { IntegrationApp } from './integration-app.js';

export interface GeneratedDocument {
  id: string;
  name: string;
  confidentiality: string;
  /** The first bytes of the stored file ("%PDF-" for a PDF). */
  header: string;
}

/** The documents of the given type kept for an investor, found by its demo account. */
export async function generatedDocuments(
  ctx: IntegrationApp,
  type: string,
  email: string,
  issuanceId: string,
): Promise<GeneratedDocument[]> {
  const { rows } = await ctx.admin.query<{
    id: string;
    name: string;
    confidentiality: string;
    storage_key: string;
  }>(
    `SELECT d.id, d.name, d.confidentiality, v.storage_key
     FROM core.document d
     JOIN core.document_version v ON v.document_id = d.id
     JOIN iam.user u ON u.investor_id = d.investor_id
     WHERE d.type = $1 AND u.email = $2 AND d.issuance_id = $3`,
    [type, email, issuanceId],
  );
  return Promise.all(
    rows.map(async (row) => ({
      id: row.id,
      name: row.name,
      confidentiality: row.confidentiality,
      header: (await ctx.storage.get(row.storage_key)).subarray(0, 5).toString('latin1'),
    })),
  );
}
