// Formatting of generated documents, from exact decimal strings (never through a float).

export type DocumentLocale = 'en-GB' | 'fr-FR';

/** "2500.00" EUR → "€2,500.00" / "2 500,00 €". */
export function formatMoney(value: string, currency: string, locale: DocumentLocale): string {
  return new Intl.NumberFormat(locale, { style: 'currency', currency }).format(
    value as Intl.StringNumericLiteral,
  );
}

/** A decimal ("0.05") as a percentage ("5 %"), every decimal kept. */
export function formatPercent(fraction: string, locale: DocumentLocale): string {
  return new Intl.NumberFormat(locale, { style: 'percent', maximumFractionDigits: 6 }).format(
    fraction as Intl.StringNumericLiteral,
  );
}

/** A business date ("2026-09-15") as "15 September 2026" / "15 septembre 2026". */
export function formatDay(date: string, locale: DocumentLocale): string {
  return new Intl.DateTimeFormat(locale, { dateStyle: 'long', timeZone: 'UTC' }).format(
    new Date(`${date}T00:00:00Z`),
  );
}

/** An instant in Paris time, e.g. "26 September 2026 at 10:05". */
export function formatInstant(instant: Date, locale: DocumentLocale): string {
  return new Intl.DateTimeFormat(locale, {
    dateStyle: 'long',
    timeStyle: 'short',
    timeZone: 'Europe/Paris',
  }).format(instant);
}

/** The mention of SPEC §3.3 on every generated document. */
export const DEMO_FOOTER: Record<DocumentLocale, string> = {
  'en-GB': 'DEMONSTRATION — fictitious data, no legal value. Generated by Veris Assets.',
  'fr-FR': 'DÉMONSTRATION — données fictives, sans valeur juridique. Généré par Veris Assets.',
};
