// Permission catalogue and role × permission matrix (SPEC §4.7, docs/DATA_MODEL.md §5).
// Single source: the API seeds the database from it and checks every route against it, the web app
// shows menus from it, and the authorisation tests are generated from it. Generated from the
// validated matrix of docs/DATA_MODEL.md; any change must be made in both places.

export const ROLE_CODES = [
  'PLATFORM_ADMIN',
  'ISSUER_ADMIN',
  'ISSUER_OPERATOR',
  'COMPLIANCE_OFFICER',
  'AUDITOR',
  'INVESTOR',
] as const;
export type RoleCode = (typeof ROLE_CODES)[number];

export const PERMISSIONS = {
  'tenant:read': 'List and view organisations',
  'tenant:manage': 'Create, update, activate and deactivate organisations',
  'platform-settings:manage': 'Global settings',
  'platform-metrics:read': 'Platform metrics and technical logs',
  'notification-template:manage': 'Email and notification templates',
  'reference-data:manage': 'Global reference data',
  'break-glass:request': 'Temporary exceptional access to a tenant',
  'user:read': "View the organisation's users",
  'user:manage': 'Invite, update and deactivate users',
  'role:assign': 'Assign roles',
  'tenant-settings:manage': 'Organisation settings',
  'investor:read': 'View investors',
  'investor:manage': 'Create and update investors',
  'investor-personal-data:read': 'Representatives and beneficial owners',
  'profile:manage': 'Complete own investor profile',
  'kyc:read': 'View KYC/KYB cases',
  'kyc:prepare': 'Open and prepare a KYC/KYB case',
  'kyc:decide': 'Approve or reject a KYC/KYB case',
  'eligibility:read': 'View eligibility assessments',
  'eligibility:decide': 'Set eligibility or suspend an investor',
  'compliance-comment:create': 'Add a compliance comment',
  'issuance:read': 'View issuances',
  'issuance:edit': 'Create and edit draft issuances',
  'issuance:submit': 'Submit an issuance for review',
  'issuance:approve': 'Approve an issuance or send it back to draft',
  'issuance:operate': 'Open and close subscriptions, activate, mature',
  'issuance:cancel': 'Cancel an issuance',
  'invitation:manage': 'Invite investors to an issuance',
  'subscription:read': 'View subscriptions',
  'subscription:create': 'Enter and submit a subscription',
  'subscription:review': 'Take a subscription under review',
  'subscription:approve': 'Approve or reject a subscription',
  'subscription:cancel': 'Cancel a subscription',
  'payment:prepare': 'Prepare the confirmation of a mock payment',
  'payment:confirm': 'Confirm a mock payment',
  'allocation:prepare': 'Enter an allocation round',
  'allocation:validate': 'Validate an allocation round',
  'registry:read': 'View the registry, positions and ledger',
  'registry-correction:request': 'Propose a CORRECTION entry',
  'registry-correction:approve': 'Approve a CORRECTION entry',
  'transfer:read': 'View transfers',
  'transfer:request': 'Request a transfer',
  'transfer:approve': 'Approve or reject a transfer',
  'transfer:cancel': 'Cancel a transfer',
  'distribution:read': 'View distributions',
  'distribution:prepare': 'Calculate, submit and generate payment instructions',
  'distribution:approve': 'Approve a distribution',
  'distribution:cancel': 'Cancel a distribution',
  'document:read': 'View non-confidential documents',
  'document:read-confidential': 'View confidential documents (KYC)',
  'document:upload': 'Upload a document',
  'task:read': '"To do" queue',
  'report:read': 'Dashboards and indicators',
  'report:export': 'CSV/PDF exports',
  'audit:read': "The organisation's audit log",
  'notification:read': 'Own notifications',
} as const;
export type Permission = keyof typeof PERMISSIONS;
export const PERMISSION_CODES = Object.keys(PERMISSIONS) as Permission[];

/** 'all': every row of the tenant; 'own': only the investor's own data ("P" in the matrix). */
export type PermissionScope = 'all' | 'own';

export const ROLE_PERMISSIONS: Record<RoleCode, Partial<Record<Permission, PermissionScope>>> = {
  PLATFORM_ADMIN: {
    'tenant:read': 'all',
    'tenant:manage': 'all',
    'platform-settings:manage': 'all',
    'platform-metrics:read': 'all',
    'notification-template:manage': 'all',
    'reference-data:manage': 'all',
    'break-glass:request': 'all',
    'notification:read': 'all',
  },
  ISSUER_ADMIN: {
    'user:read': 'all',
    'user:manage': 'all',
    'role:assign': 'all',
    'tenant-settings:manage': 'all',
    'investor:read': 'all',
    'investor:manage': 'all',
    'investor-personal-data:read': 'all',
    'kyc:read': 'all',
    'kyc:prepare': 'all',
    'eligibility:read': 'all',
    'issuance:read': 'all',
    'issuance:edit': 'all',
    'issuance:submit': 'all',
    'issuance:approve': 'all',
    'issuance:operate': 'all',
    'issuance:cancel': 'all',
    'invitation:manage': 'all',
    'subscription:read': 'all',
    'subscription:review': 'all',
    'subscription:approve': 'all',
    'subscription:cancel': 'all',
    'payment:prepare': 'all',
    'payment:confirm': 'all',
    'allocation:prepare': 'all',
    'allocation:validate': 'all',
    'registry:read': 'all',
    'registry-correction:request': 'all',
    'registry-correction:approve': 'all',
    'transfer:read': 'all',
    'transfer:approve': 'all',
    'transfer:cancel': 'all',
    'distribution:read': 'all',
    'distribution:prepare': 'all',
    'distribution:approve': 'all',
    'distribution:cancel': 'all',
    'document:read': 'all',
    'document:read-confidential': 'all',
    'document:upload': 'all',
    'task:read': 'all',
    'report:read': 'all',
    'report:export': 'all',
    'audit:read': 'all',
    'notification:read': 'all',
  },
  ISSUER_OPERATOR: {
    'investor:read': 'all',
    'investor:manage': 'all',
    'investor-personal-data:read': 'all',
    'kyc:read': 'all',
    'kyc:prepare': 'all',
    'eligibility:read': 'all',
    'issuance:read': 'all',
    'issuance:edit': 'all',
    'issuance:submit': 'all',
    'invitation:manage': 'all',
    'subscription:read': 'all',
    'subscription:review': 'all',
    'subscription:cancel': 'all',
    'payment:prepare': 'all',
    'allocation:prepare': 'all',
    'registry:read': 'all',
    'transfer:read': 'all',
    'distribution:read': 'all',
    'distribution:prepare': 'all',
    'document:read': 'all',
    'document:read-confidential': 'all',
    'document:upload': 'all',
    'task:read': 'all',
    'report:read': 'all',
    'notification:read': 'all',
  },
  COMPLIANCE_OFFICER: {
    'investor:read': 'all',
    'investor-personal-data:read': 'all',
    'kyc:read': 'all',
    'kyc:decide': 'all',
    'eligibility:read': 'all',
    'eligibility:decide': 'all',
    'compliance-comment:create': 'all',
    'issuance:read': 'all',
    'subscription:read': 'all',
    'registry:read': 'all',
    'registry-correction:approve': 'all',
    'transfer:read': 'all',
    'transfer:approve': 'all',
    'distribution:read': 'all',
    'document:read': 'all',
    'document:read-confidential': 'all',
    'task:read': 'all',
    'report:read': 'all',
    'audit:read': 'all',
    'notification:read': 'all',
  },
  AUDITOR: {
    'user:read': 'all',
    'investor:read': 'all',
    'kyc:read': 'all',
    'eligibility:read': 'all',
    'issuance:read': 'all',
    'subscription:read': 'all',
    'registry:read': 'all',
    'transfer:read': 'all',
    'distribution:read': 'all',
    'document:read': 'all',
    'report:read': 'all',
    'report:export': 'all',
    'audit:read': 'all',
    'notification:read': 'all',
  },
  INVESTOR: {
    'profile:manage': 'own',
    'kyc:read': 'own',
    'issuance:read': 'own',
    'subscription:read': 'own',
    'subscription:create': 'own',
    'subscription:cancel': 'own',
    'registry:read': 'own',
    'transfer:read': 'own',
    'transfer:request': 'own',
    'transfer:cancel': 'own',
    'distribution:read': 'own',
    'document:read': 'own',
    'document:read-confidential': 'own',
    'document:upload': 'own',
    'notification:read': 'all',
  },
};

/** Permissions of a set of roles, the broadest scope winning. */
export function permissionsOf(roles: readonly RoleCode[]): Map<Permission, PermissionScope> {
  const granted = new Map<Permission, PermissionScope>();
  for (const role of roles) {
    for (const [permission, scope] of Object.entries(ROLE_PERMISSIONS[role]) as [
      Permission,
      PermissionScope,
    ][]) {
      if (granted.get(permission) !== 'all') granted.set(permission, scope);
    }
  }
  return granted;
}
