// Column conventions of SPEC §21.2, shared by every table definition.
import { sql } from 'drizzle-orm';
import { integer, timestamp, uuid } from 'drizzle-orm/pg-core';

/** UUID v7 primary key (time-ordered), generated by PostgreSQL 18 when not provided. */
export const id = () =>
  uuid()
    .primaryKey()
    .default(sql`uuidv7()`);

/** Technical timestamp, always `timestamptz` (UTC). */
export const utcTimestamp = () => timestamp({ withTimezone: true, mode: 'date' });

/** Tenant of the row. Isolation is enforced by row level security (see the security migrations). */
export const tenantId = () => uuid().notNull();

/** Common columns of mutable tables: creation, last update, author and optimistic lock version. */
export const auditColumns = () => ({
  createdAt: utcTimestamp().notNull().defaultNow(),
  updatedAt: utcTimestamp().notNull().defaultNow(),
  createdBy: uuid(),
  version: integer().notNull().default(1),
});
