import { Inject, Injectable, Logger, type OnApplicationBootstrap } from '@nestjs/common';
import { EXPORT_PERMISSIONS, type ExportKind } from '@veris/shared';
import { and, asc, desc, eq, ne } from 'drizzle-orm';
import { AuditWriter } from '../../../core/audit/audit-writer.js';
import { currentUser } from '../../../core/context/request-context.js';
import {
  DATABASE,
  type Database,
  type Transaction,
  withCurrentTenant,
  withTenantTransaction,
} from '../../../core/database/database.js';
import { toCsv, type CsvCell } from '../../../core/documents/csv.js';
import { DocumentsService } from '../../../core/documents/documents.service.js';
import { AppError } from '../../../core/errors/app-error.js';
import { JobQueue } from '../../../core/jobs/job-queue.js';
import { QUEUES } from '../../../core/jobs/queues.js';
import { Outbox } from '../../../core/outbox/outbox.js';
import { exportRequest } from '../infrastructure/schema.js';
import {
  auditExport,
  distributionLineExport,
  issuanceFigures,
  registryExport,
  subscriptionExport,
} from '../infrastructure/views.js';

export type ExportRow = typeof exportRequest.$inferSelect;

/** Data of the `export-generation` job: identifiers only. */
export interface ExportJob {
  tenantId: string;
  exportId: string;
}

export const EXPORT_EVENTS = { ready: 'reporting.export.ready' } as const;

const MENTION = 'DEMONSTRATION - fictitious data - no legal value - generated by Veris Assets';

interface ExportTable {
  header: string[];
  rows: CsvCell[][];
}

/**
 * CSV exports (SPEC §18, docs/BACKLOG.md P15-3). An export is asked for, then generated in the
 * background (`export-generation` job) from the reporting views, kept as an internal REPORT
 * document of the organisation, and its requester is told when it is ready.
 */
@Injectable()
export class ExportsService implements OnApplicationBootstrap {
  private readonly logger = new Logger(ExportsService.name);

  constructor(
    @Inject(DATABASE) private readonly db: Database,
    private readonly jobs: JobQueue,
    private readonly documents: DocumentsService,
    private readonly audit: AuditWriter,
    private readonly outbox: Outbox,
  ) {}

  async onApplicationBootstrap(): Promise<void> {
    await this.jobs.work<ExportJob>(QUEUES.exportGeneration.name, (job) => this.generate(job));
  }

  /** Asks for an export; the kind needs its own permission on the whole organisation. */
  request(kind: ExportKind, issuanceId: string | null): Promise<ExportRow> {
    const user = currentUser();
    if (user.permissions.get(EXPORT_PERMISSIONS[kind]) !== 'all') {
      throw new AppError('PERMISSION_DENIED');
    }
    return withCurrentTenant(this.db, async (tx, tenantId) => {
      if (issuanceId) {
        const [found] = await tx
          .select({ id: issuanceFigures.issuanceId })
          .from(issuanceFigures)
          .where(eq(issuanceFigures.issuanceId, issuanceId));
        if (!found) throw new AppError('RESOURCE_NOT_FOUND');
      }
      const [created] = await tx
        .insert(exportRequest)
        .values({
          tenantId,
          requestedBy: user.userId,
          kind,
          params: issuanceId && kind !== 'AUDIT' ? { issuanceId } : {},
        })
        .returning();
      await this.audit.recordIn(tx, {
        tenantId,
        action: 'EXPORT_REQUESTED',
        resourceType: 'export',
        resourceId: created!.id,
        newValue: { kind, issuanceId },
        result: 'SUCCESS',
      });
      const job: ExportJob = { tenantId, exportId: created!.id };
      await this.jobs.sendIn(tx, QUEUES.exportGeneration.name, job);
      return created!;
    });
  }

  /** The user's own exports, the latest first. */
  list(): Promise<ExportRow[]> {
    return withCurrentTenant(this.db, (tx) =>
      tx
        .select()
        .from(exportRequest)
        .where(eq(exportRequest.requestedBy, currentUser().userId))
        .orderBy(desc(exportRequest.createdAt))
        .limit(50),
    );
  }

  get(id: string): Promise<ExportRow> {
    return withCurrentTenant(this.db, async (tx) => {
      const [found] = await tx
        .select()
        .from(exportRequest)
        .where(and(eq(exportRequest.id, id), eq(exportRequest.requestedBy, currentUser().userId)));
      if (!found) throw new AppError('RESOURCE_NOT_FOUND');
      return found;
    });
  }

  /**
   * The `export-generation` job: marked RUNNING, then the CSV and its document in one
   * transaction. Run twice, it does nothing the second time; a failure is kept on the request,
   * and the job is retried.
   */
  async generate(job: ExportJob): Promise<void> {
    const started = await withTenantTransaction(this.db, job.tenantId, (tx) =>
      tx
        .update(exportRequest)
        .set({ status: 'RUNNING' })
        .where(and(eq(exportRequest.id, job.exportId), ne(exportRequest.status, 'DONE')))
        .returning({ id: exportRequest.id }),
    );
    if (started.length === 0) return;
    try {
      await withTenantTransaction(this.db, job.tenantId, async (tx) => {
        const [found] = await tx
          .select()
          .from(exportRequest)
          .where(eq(exportRequest.id, job.exportId))
          .for('update');
        if (!found || found.status === 'DONE') return;
        await this.run(tx, found);
      });
    } catch (error) {
      this.logger.error({ err: error, exportId: job.exportId }, 'Export generation failed');
      await withTenantTransaction(this.db, job.tenantId, (tx) =>
        tx
          .update(exportRequest)
          .set({ status: 'FAILED', error: 'GENERATION_FAILED', finishedAt: new Date() })
          .where(eq(exportRequest.id, job.exportId)),
      );
      throw error;
    }
  }

  private async run(tx: Transaction, found: ExportRow): Promise<void> {
    const kind = found.kind as ExportKind;
    const issuanceId = (found.params as { issuanceId?: string }).issuanceId ?? null;
    const table = await this.table(tx, kind, issuanceId);
    const stamp = found.createdAt.toISOString().slice(0, 16).replace(/[-:]/g, '').replace('T', '-');
    const stored = await this.documents.storeGenerated(tx, found.tenantId, {
      type: 'REPORT',
      name: `export-${kind.toLowerCase()}-${stamp}-${found.id.slice(0, 8)}.csv`,
      confidentiality: 'INTERNAL',
      ownerType: 'TENANT',
      issuanceId,
      content: toCsv(MENTION, table.header, table.rows),
      mimeType: 'text/csv',
    });
    await tx
      .update(exportRequest)
      .set({
        status: 'DONE',
        documentId: stored.id,
        rowCount: table.rows.length,
        error: null,
        finishedAt: new Date(),
      })
      .where(eq(exportRequest.id, found.id));
    await this.audit.recordIn(tx, {
      tenantId: found.tenantId,
      actorUserId: null,
      action: 'EXPORT_GENERATED',
      resourceType: 'export',
      resourceId: found.id,
      newValue: { kind, rows: table.rows.length, documentId: stored.id },
      result: 'SUCCESS',
    });
    await this.outbox.publish(tx, {
      tenantId: found.tenantId,
      eventType: EXPORT_EVENTS.ready,
      aggregateType: 'export',
      aggregateId: found.id,
      payload: { requestedBy: found.requestedBy, kind },
    });
  }

  private async table(
    tx: Transaction,
    kind: ExportKind,
    issuanceId: string | null,
  ): Promise<ExportTable> {
    switch (kind) {
      case 'REGISTRY': {
        const rows = await tx
          .select()
          .from(registryExport)
          .where(issuanceId ? eq(registryExport.issuanceId, issuanceId) : undefined)
          .orderBy(
            asc(registryExport.issuanceCode),
            asc(registryExport.accountType),
            asc(registryExport.investorName),
          );
        return {
          header: [
            'issuance_code',
            'account_type',
            'account_id',
            'investor_id',
            'investor_name',
            'quantity_held',
            'quantity_blocked',
            'quantity_available',
            'nominal_value',
            'nominal_amount',
            'currency',
            'updated_at',
          ],
          rows: rows.map((row) => [
            row.issuanceCode,
            row.accountType,
            row.accountId,
            row.investorId,
            row.investorName,
            row.quantityHeld,
            row.quantityBlocked,
            row.quantityAvailable,
            row.nominalValue,
            row.nominalAmount,
            row.currency,
            row.updatedAt,
          ]),
        };
      }
      case 'SUBSCRIPTIONS': {
        const rows = await tx
          .select()
          .from(subscriptionExport)
          .where(issuanceId ? eq(subscriptionExport.issuanceId, issuanceId) : undefined)
          .orderBy(asc(subscriptionExport.issuanceCode), asc(subscriptionExport.createdAt));
        return {
          header: [
            'subscription_id',
            'issuance_code',
            'investor_id',
            'investor_name',
            'status',
            'requested_units',
            'requested_amount',
            'allocated_units',
            'amount_due',
            'currency',
            'payment_reference',
            'submitted_at',
            'decided_at',
            'rejection_reason',
            'cancellation_reason',
          ],
          rows: rows.map((row) => [
            row.subscriptionId,
            row.issuanceCode,
            row.investorId,
            row.investorName,
            row.status,
            row.requestedUnits,
            row.requestedAmount,
            row.allocatedUnits,
            row.amountDue,
            row.currency,
            row.paymentReference,
            row.submittedAt,
            row.decidedAt,
            row.rejectionReason,
            row.cancellationReason,
          ]),
        };
      }
      case 'DISTRIBUTIONS': {
        const rows = await tx
          .select()
          .from(distributionLineExport)
          .where(issuanceId ? eq(distributionLineExport.issuanceId, issuanceId) : undefined)
          .orderBy(
            asc(distributionLineExport.issuanceCode),
            asc(distributionLineExport.sequence),
            asc(distributionLineExport.investorName),
          );
        return {
          header: [
            'distribution_id',
            'issuance_code',
            'payment_no',
            'type',
            'status',
            'record_date',
            'payment_date',
            'investor_id',
            'investor_name',
            'account_id',
            'eligible_units',
            'gross_amount_unrounded',
            'gross_amount',
            'currency',
          ],
          rows: rows.map((row) => [
            row.distributionId,
            row.issuanceCode,
            row.sequence,
            row.type,
            row.status,
            row.recordDate,
            row.paymentDate,
            row.investorId,
            row.investorName,
            row.accountId,
            row.eligibleQuantity,
            row.grossAmountUnrounded,
            row.grossAmount,
            row.currency,
          ]),
        };
      }
      case 'AUDIT': {
        const rows = await tx
          .select()
          .from(auditExport)
          .orderBy(asc(auditExport.occurredAt), asc(auditExport.auditEventId));
        return {
          header: [
            'occurred_at',
            'actor_user_id',
            'actor_name',
            'actor_role',
            'action',
            'resource_type',
            'resource_id',
            'result',
            'reason',
            'source',
            'correlation_id',
          ],
          rows: rows.map((row) => [
            row.occurredAt,
            row.actorUserId,
            row.actorName,
            row.actorRole,
            row.action,
            row.resourceType,
            row.resourceId,
            row.result,
            row.reason,
            row.source,
            row.correlationId,
          ]),
        };
      }
    }
  }
}
